### PR TITLE
upgrade 2.12

### PR DESCRIPTION
**Pull request by mcharriere**
This PR
- Upgrade to 2.12.1 with vendir

towards https://github.com/giantswarm/giantswarm/issues/23766 and https://github.com/giantswarm/giantswarm/issues/23384

## Checklist

- [ ] Automated test are working (for chart changes)
- [ ] I am confident my changes don't break existing installations (for chart changes)
- [ ] Changelog entry has been added

### CODE REVIEW

**Comment by webwurst** [comment]
Cool! Just two random thoughts:
- We once decided to remove the `-app` suffix for Chart names in general. Only exception would be for the repository name.
- We want to switch to `main` as the default branch instead of `master`.

I don't know if this makes sense for this PR, but if possible it would be nice since this upgrade comes anyway with breaking changes. Might be harder in the future.

**Comment by webwurst** [comment]
> > I don't know if this makes sense for this PR, but if possible it would be nice since this upgrade comes anyway with breaking changes. Might be harder in the future.
> 
> I can remove the app in this PR, but now that we are not using subcharts; this PR has no breaking changes.

I thought with upstream `2.12.x` came many changes, so that customers need to take care anyway. And that's why it might still be a good place for us to clean up a bit..

> Switching from master to main should not bring problems with the app, right?

Yeah, probably not, maybe some automation could be confused, but on the other hand we already moved other repos so fixed might already be in place.

**Review by ced0ps — APPROVED** [review]
LGTMIT
I agree that we should omit the *-app suffix everywhere but in the repo name.

**Comment by mcharriere** [comment]
I made the change to remove the subfix app from everywhere except the repo.

The upgrade path works fine, changing the name in the app definition does the trick. Something like:

```diff
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: linkerd2-cni-app
  namespace: mv88j
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
-  name: linkerd2-cni-app
+  name: linkerd2-cni
  namespace: linkerd-cni
  namespaceConfig:
    annotations:
      linkerd.io/inject: disabled
    labels:
      linkerd.io/cni-resource: "true"
      config.linkerd.io/admission-webhooks: disabled
- version: 0.7.4
+  version: 0.8.0
```

**Comment by mcharriere** [comment]
Small guide for reviewers:

You can ignore the files under `helm/linkerd2-cni-app/charts` and `helm/linkerd2-cni-app/templates`. 
They are coming directly from https://github.com/giantswarm/linkerd2-upstream/tree/giantswarm/main.

The rest is up for review.

**Review by ced0ps — APPROVED** [review]
LGTM

**Pull request merged**
